spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ConnorLH/springcloud-config-repo.git
          username: ConnorLH
          password: Corner901226
          basedir: F:\data\cloudrepo
  rabbitmq:
    host: 192.168.25.131
    port: 5672
    username: admin
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
